apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-oauth-token
    backendType: vault
    mandatory: true
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  defaults:
    backendType: vault

