# Source: tekton/templates/250-docker-secret.yaml
apiVersion: v1
data:
  password: ""
  username: ""
kind: Secret
metadata:
  name: knative-docker-user-pass
  annotations:
    tekton.dev/docker-0: ""
type: kubernetes.io/basic-auth
