# Source: tekton/templates/250-git-secret.yaml
apiVersion: v1
data:
  password: ""
  username: ""
kind: Secret
metadata:
  name: knative-git-user-pass
  annotations:
    tekton.dev/git-0: "https://github.com"
type: kubernetes.io/basic-auth
