---
# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: complex-secret
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.633"
    release: "lighthouse"
    heritage: "Helm"
type: Opaque
data:
  username: ""
  password: ""
