---
# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unspecified-complex-type
  labels:
    app: external-dns
    chart: "external-dns-0.5.3"
    release: "external-dns"
    heritage: "Helm"
type: Opaque
data:
  hmac: ""
  git_token: ""
