apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    gitops.jenkins-x.io/pipeline: environment
  name: jenkins-x-bucketrepo
  namespace: jx
spec:
  backendType: vault
  data:
  - key: secret/data/jx/adminUser
    name: BASIC_AUTH_PASS
    property: password
  - key: secret/data/jx/adminUser
    name: BASIC_AUTH_USER
    property: username
  template:
    metadata:
      annotations:
        jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
        jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
        jenkins.io/foo: bar
      labels:
        jenkins.io/credentials-type: usernamePassword
        release: jenkins-x
    type: Opaque
  vaultMountPoint: kubernetes
  vaultRole: vault-infra