apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    gitops.jenkins-x.io/pipeline: environment
  name: lighthouse-hmac-token
  namespace: jx
spec:
  backendType: vault
  data:
  - key: secret/data/lighthouse/hmac
    name: hmac
    property: token
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: lighthouse-0.0.633
        heritage: Helm
        release: lighthouse
    type: Opaque
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
