apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: complex-secret
    backendType: azureKeyVault
    azureKeyVault:
      keyVaultName: appleTree
    mappings:
      - name: username
        key: secretSquirrel
        property: username
      - name: password
        key: secretSquirrel
        property: password
  - name: simple-secret
    backendType: azureKeyVault
    azureKeyVault:
      keyVaultName: bananaPalm
    mappings:
      - name: azure.json
        key: azure-secret-name
  - name: simple-secret-property
    backendType: azureKeyVault
    azureKeyVault:
      keyVaultName: mangroveSwamp
    mappings:
      - name: azure.json
        key: azure-secret-name
        property: customProperty
  defaults:
    backendType: azureKeyVault
    azureKeyVault:
      keyVaultName: twilightSparkle
