apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: complex-secret
    backendType: secretsManager
    roleArn: acs:ram::{UID}:role/custom
    region: us-east-2
    mappings:
      - name: username
        key: secretSquirrel
        property: username
      - name: password
        key: secretSquirrel
        property: password
        versionStage: CustomVersion
  - name: simple-secret
    backendType: secretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
  - name: simple-secret-property
    backendType: secretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
        property: customProperty
  defaults:
    backendType: secretsManager
    roleArn: acs:ram::{UID}:role/demo
    region: us-east-1
    versionStage: AWSPREVIOUS
