apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: secretsManager
  secrets:
  - backendType: secretsManager
    mappings:
    - key: jx-basic-auth-user
      name: username
      property: username
    name: jx-basic-auth-user-password
  - backendType: secretsManager
    mappings:
    - key: jx-basic-auth-htpasswd
      name: auth
    name: jx-basic-auth-htpasswd
