---
# Source: lighthouse/templates/hmacsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lighthouse-hmac-token
  annotations:
    secret.jenkins-x.io/prefix: staging
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.633"
    release: "lighthouse"
    heritage: "Helm"
type: Opaque
data:  
  hmac: ""