apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
    - name: lighthouse-hmac-token
      properties:
      - name: token
        question: Lighthouse webhook token
        help: The webhook token is used as a secret to verify webhooks come from a trusted source
        format: hmac
    - name: jenkins-x-bucketrepo
      properties:
      - name: username
        question: bucket repository user name
        help: The username used to authenticate with the bucket repository
        defaultValue: admin
      - name: password
        question: bucket repository password
        help: The password to authenticate with the bucket repository
        minLength: 5
        maxLength: 41
        generate: true
    - name: knative-docker-user-pass
      properties:
      - name: password
        question: Docker Registry password
        help: The password used to access the external docker registry
        generate: true
