apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-oauth-token1
    backendType: vault
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  - name: my-kubernetes-secret-name
    backendType: gcpSecretsManager
    mappings:
    - name: oauth
      key: my-gsm-secret-name
      property: value
    gcpSecretsManager:
      version: 1
      uniquePrefix: bar

