apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: complex-secret
    backendType: ibmcloudSecretsManager
    mappings:
      - name: username
        key: secretSquirrel
        property: username
      - name: password
        key: secretSquirrel
        property: password
  - name: simple-secret
    backendType: ibmcloudSecretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
  - name: simple-secret-property
    backendType: ibmcloudSecretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
        property: customProperty
  defaults:
    backendType: ibmcloudSecretsManager
