apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
    - name: my-kubernetes-secret-name1
      backendType: gcpSecretsManager
      mappings:
        - name: oauth
          key: my-gsm-secret-name
          property: value
    - name: my-kubernetes-secret-name2
      backendType: gcpSecretsManager
      mappings:
        - name: oauth
          key: my-gsm-secret-name
          property: value
  defaults:
    backendType: gcpSecretsManager
