apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: complex-secret
    backendType: alicloudSecretsManager
    roleArn: acs:ram::{UID}:role/custom
    mappings:
      - name: username
        key: secretSquirrel
        property: username
      - name: password
        key: secretSquirrel
        property: password
        versionStage: CustomVersion
  - name: simple-secret
    backendType: alicloudSecretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
  - name: simple-secret-property
    backendType: alicloudSecretsManager
    mappings:
      - name: azure.json
        key: azure-secret-name
        property: customProperty
  defaults:
    backendType: alicloudSecretsManager
    roleArn: acs:ram::{UID}:role/demo
    versionStage: ACSCurrent
